### ISSUE TITLE
Deprecate grantreporting.udaf.utah.gov/public

### ISSUE THREAD

**Issue by stdavis** [agrc/cemetery#10]
# Summary

The web app needs to be shut down and the data archived.

# Is the data removal temporary or permanent?

- [ ] Replaced with newer data (intials)
- [ ] Historical data for archive (intials)
- [x] No longer relevant (sd)

# Where does the data live?

- [ ] ArcGIS Online (intials)
  - [ ] Action taken (intials)
- [ ] Internal SGID (intials)
  - [ ] Action taken (intials)
- [x] External SGID (sd)
  - [x] Action taken - database backup uploaded to [drive](https://drive.google.com/drive/u/1/folders/1G8l2Me-6rFc3t7r74RLE0OuFtcKMjic0)(sd)
  - [ ] Request shut down of sql server database (initials)
- [ ] Google Drive (intials)
  - [ ] Action taken (intials)
- [ ] Open data (intials)
  - [ ] Action taken (intials)
- [ ] Mapserv (intials)
  - [ ] Action taken (intials)
- [ ] gis.utah.gov data pages (intials)
  - [ ] Action taken (intials)
- [ ] Stewardship doc and sgid-index (intials)
  - [ ] Action taken (intials)

# Is there a website?
http://grantreporting.udaf.utah.gov/

- [x] Is the source code on GitHub? (sd)
  - https://github.com/agrc/acts-statistics
- [x] Should it be archived? yes (sd)
  - [x] Action taken - archived (sd)
- [x] Should it be removed from the web server or show a static page with information? (sd)
  - [x] Action taken - shut down app pools related to this site on .126 (sd)
- [ ] Should it redirect somewhere else? (intials)
  - [ ] Action taken (intials)

# Is there a map service?

- [x] Should it be stopped or deleted? (sd)
  - [x] Action taken - map service deleted from mapserv (sd)

# Is there a forklift pallet?

- [x] Should it continue to run or be removed? (sd)
  - [x] Removed pallet from production forklift (sd)
- [x] Should stale data be removed from forklift hashing and receiving? (sd)
  - [x] Action taken (sd) - removed from production servers as well

# Are there service dependencies?

- [ ] Does the web api query it? (intials)
  - [ ] Action taken (intials)
- [ ] Do AGRC or applications widgets reference it? (intials)
  - [ ] Action taken (intials)

**Comment by stdavis** [comment]
Also, disabled `forkliftDropoff.py` scheduled task on 126.

**Comment by stdavis** [comment]
Scratch that. I realized that `forkliftDropoff.py` has UDSH data in it as well. So I turned it back on.

**Comment by stdavis** [comment]
Do we need to request that the SQL database be shut down and removed? I requested a backup today for it. I was able to get Catalog to copy all of the datasets to an FGDB except for one table: `salinity.SALINITYADMIN.AdminCost&PracticeAttribute_View`. I'm guessing that it's due to the `&` in the table name. I tried to rename it but got a database error message. I was able to get an XML export (data and schema) to work.

I've put the SQL backup, FGDB and XML export into: https://drive.google.com/drive/u/1/folders/1G8l2Me-6rFc3t7r74RLE0OuFtcKMjic0

I'm not sure how useful the XML export is. I tried importing it into a new FGDB and it errored out. Something about a duplicate field name.

**Comment by steveoh** [comment]
There is a scheduled task for contract expiration they should be removed

**Comment by steveoh** [comment]
This app is also in the /applications section of our website I think

**Comment by stdavis** [comment]
> There is a scheduled task for contract expiration that should be removed

I've disabled it.

**Comment by stdavis** [comment]
> This app is also in the /applications section of our website I think

https://github.com/agrc/gis.utah.gov/pull/1231

**Comment by steveoh** [comment]
I think this is done.

**Comment by steveoh** [comment]
ps - I zipped a few more folders and added them to drive

- the acts, udaf, and udaf.features web projects projects
- the contract pdf's etc from c:\arcgisserver\projectdata
- the server projects mxds
