### ISSUE TITLE
Deprecate SGID10.ENVIRONMENT.DWQMonitoredLakes132

### ISSUE THREAD

**Issue by stdavis** [agrc/cemetery#12]
# Summary

This layer is a duplicate of `SGID10.ENVIRONMENT.DWQAssessedLakes` and needs to be removed.

From Mark Stanger
>Yes, you should delete `SGID10.ENVIRONMENT.DWQMonitoredLakes132` from the SGID as it is old and not as accurate regarding the lakes we (DWQ) monitor and assess for water quality.

# Remove data from the following areas

- [x] ArcGIS Online (intials) @stdavis
- [x] Internal SGID (intials) @MichaelAGRC
- [x] External SGID (intials) @MichaelAGRC 
- [x] Google Drive (sd) 
- [x] Open data (intials) @stdavis
- [x] Stewardship doc and sgid-index (intials) @ZachBeck 

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh)

**Comment by steveoh** [comment]
would you add names like that? @stdavis

**Comment by stdavis** [comment]
I think that could work.

**Comment by ZachBeck** [comment]
remind me what you want me to do... Is it just add the github issue to the stewardship doc?

**Comment by steveoh** [comment]
@ZachBeck that is what it looks like yup.

**Comment by stdavis** [comment]
@ZachBeck Any updates on this issue?

**Comment by ZachBeck** [comment]
it's done now

**Comment by stdavis** [comment]
@MichaelAGRC Would you be able to remove `SGID10.ENVIRONMENT.DWQMonitoredLakes132` from SGID internal and external?

**Comment by stdavis** [comment]
Ping @MichaelAGRC. Just looking for an update. Thanks!

**Comment by stdavis** [comment]
I removed this table from `SGID.META.AGOLItems`, deleted the service definition in AGOL and marked the feature layer in AGOL as deprecated.

**Comment by MichaelAGRC** [comment]
I've removed the data from SGID, and changed the privileges in SGID10 so that agrc and SearchAPI can't see it.

**Comment by steveoh** [comment]
awesome. i think this is done then.
