### ISSUE TITLE
Deprecate SGID.POLITICAL.UtahSchoolBoardDistricts_Members

### ISSUE THREAD

**Issue by stdavis** [agrc/cemetery#13]
# Summary

In an email from @mheagin on 12/3/19:
>I was updating some data and noticed our SGID.POLITICAL.UtahSchoolBoardDistricts_Members is the same as SGID.POLITICAL.UtahSchoolBoardDistricts2015. 
I thought the "_Members" was created because the Board members names were not part of the original "..Districts2015 data, it may have been the "2012" version.
Any way since they are now both identical I believe we can eliminate the "_Members" version (see attachment).
Since that was the one I had been updating we need to push the button to get  UtahSchoolBoardDistricts2015 (855c45da6d2e4386b06cfa27229f9685 ) updated in AGOL too. Everything is updated in the ...Distircts2015 on SGID now.

# Remove data from the following areas

- [x] ArcGIS Online (mf)
- [x] Internal SGID (mf)
- [x] External SGID (mf)
- [x] Google Drive (intials)
- [x] Open data (mf)
- [x] gis.utah.gov data pages (sg)
- [x] Stewardship doc and sgid-index (sg)
- [x] Remove from `SGID.META.AGOLItems` (mf)

# Are there service dependencies?

- [x] Validate that the web api does not query it (sg)
- [x] Validate that AGRC or applications widgets do not reference it (sd)

**Comment by stdavis** [comment]
@MichaelAGRC Are you up for removing `SGID.POLITICAL.UtahSchoolBoardDistricts_Members` from SGID internal? I think that's the first step to this issue. Then the rest of the items can be done.

**Comment by stdavis** [comment]
Ping @MichaelAGRC

**Comment by MichaelAGRC** [comment]
I have changed the perms so that only the sde user can see it.  Do you want it removed?

**Comment by brigsz** [comment]
perfect, that is probably fine for the moment

**Comment by brigsz** [comment]
in a week we can get rid of it, if those folks are still ready to do that

**Comment by steveoh** [comment]
@MichaelAGRC did you hide the agol service as well?

**Comment by MichaelAGRC** [comment]
I have changed the sharing from Everyone to Owner.  Only UtahAGRC should be able to see it now on AGOL and OpenData.

**Comment by steveoh** [comment]
Since there are no initials and checkboxes in the issue above I went through to double check everything. Please try to keep the information above current to make this easier on everyone.

I still see this layer in the public SGID. 
Looks like it was updated in the internal sgid. 
I could not find it in open data.
It is still in the sgid index/stewardship doc
It is still in the meta table

**Comment by MichaelAGRC** [comment]
I think you can close this now.
