### ISSUE TITLE
Deprecate SGID10.PLANNING.QLTYGROWTH[...] rasters

### ISSUE THREAD

**Issue by jacobdadams** [agrc/cemetery#15]
# Summary

The three QLTYGROWTH rasters  in SGID10 are apparently from a planning scenario/forecast tool from 1998. They are out of date and, from a modern land use modelling perspective, of limited utility. We've got them marked for shelving in AGOL, but it's probably better to just let them float off into the sunset as another wrong model (rule # 1 in modelling: All models are wrong, some models are useful).

# Remove data from the following areas

- [x] Internal SGID (ZB)
- [x] (?) Google Drive (ZB)
- [x] (no action) Mapserv (@steveoh)

# Is there a map service?

- [x] (no action) Stop (@steveoh)
- [x] (no action) Delete (@steveoh)

# Is there a forklift pallet?

- [x] (no action) Remove repo (@steveoh)
- [x] (no action) Remove stale data from forklift hashing and receiving (@steveoh)

# Are there service dependencies?

- [x] (no action) Validate that the web api does not query it (@steveoh)
- [x] (no action) Validate that AGRC or applications widgets do not reference it (@steveoh)

**Comment by ZachBeck** [comment]
what would you like me to do?

**Comment by steveoh** [comment]
@ZachBeck go through these open issues and remove stuff from sgid and agol moving it to the shelved spot and updating the Stewardship page. Very similar to the others we've done. https://github.com/agrc/cemetery/issues/6#issuecomment-539515932

**Comment by ZachBeck** [comment]
no planning quality growth rasters in drive or internal sgid.

**Comment by steveoh** [comment]
ok, so edit the issue and put your initials with the check box so we know that it's done and by who

**Comment by stdavis** [comment]
Looks like all of the action items are complete for this issue.
