### ISSUE TITLE
Deprecate mapserv.utah.gov/arcgis/rest/services/Socrata/MapServer

### ISSUE THREAD

**Issue by nathankota** [agrc/cemetery#16]
# Summary

Drew Mingl has indicated that we can shut down this service, which hooks into his https://www.utah.gov/data/ site. AGRC Open Data was offered to him as an alternative, but no action has been taken yet.

Tagged:
@steveoh 
@stdavis 

# Is there a map service?

- [x] Delete (sd)

# Is there a forklift pallet?

- [x] Remove repo (sd)
- [x] Remove stale data from forklift hashing and receiving (initials)

**Comment by stdavis** [comment]
@nathankota The intention of this issue template was that the checkboxes should not be checked until the task was completed. The issue creator is supposed to delete any that you know doesn't apply. I've fixed this issue as an example.

Submit a PR to [this file](https://github.com/agrc/cemetery/blob/master/.github/ISSUE_TEMPLATE/deprecate-sgid-dataset-or-web-application.md) if you have an ideas on how to make this more clear.

Also, does Drew need us to remove the item from Socrata or was he going to take care of that? I remember having a login and doing some admin with it but it's been years.

**Comment by stdavis** [comment]
I didn't think that any data needed to be removed from hashing since all of that data is in the AGOL and Swapper pallets anyways. I also deleted `Socrata.mxd` on the share.

@nathankota Nice work on this one! This is a great one to get rid of. Next up, UtahEM?

**Comment by nathankota** [comment]
Thanks for taking care of this, and for keeping me honest with the process. I have a suggestion or two so that periodic users like me don't mess it up. Do you still need me to ask Drew about removing from Socrata @stdavis? Yes, UtahEM is in the works.
