### ISSUE TITLE
Deprecate SGID.HISTORY.ArcheologySites

### ISSUE THREAD

**Issue by brigsz** [agrc/cemetery#17]
# Summary

A short summary of the situation... State History, has some partners that feel like the hexagons are not appropriate, that 1 km is too detailed.  They would like to shut that service down.  I am a little unsure what it is connected to, It may take a bit of time to find what it is connected to

I will just try to locate some of this
# Remove data from the following areas

- [x] ArcGIS Online (zb)
- [x] Internal SGID (zb)
- [x] External SGID (zb)
- [x] Google Drive (zb)
- [x] Open data (zb)
- [x] gis.utah.gov data pages (sg)
- [x] Stewardship doc and sgid-index (sg)
- [x] `SGID.META.AGOLItems` (sd)

# Is there a forklift pallet?

- [x] Remove repo (sd)
- [x] Remove stale data from forklift hashing and receiving (sd)

# Are there service dependencies?

- [x] Validate that the web api does not query it (sg)
- [x] Validate that AGRC or applications widgets do not reference it (sg)

**Comment by steveoh** [comment]
It appears to be in AGOL and open data: https://opendata.gis.utah.gov/datasets/utah-archaeology-sites

It is also being used in a forklift pallet: https://github.com/agrc/warehouse/blob/93da6ed62839f1685cfe9d6ae8c80b8ac7f1a099/database_maintenance/History/HistoricalSitesPallet.py#L33

**Comment by stdavis** [comment]
I've checked the mapserv services and it appears that it's not used in any on that server. I confirmed that it's not in the main data folder on those machines either.

**Comment by brigsz** [comment]
Okay, this is sounding better than I thought!  Great.  I will look things over a little closer and try to think of other issues

**Comment by steveoh** [comment]
Do you want us to wait or should we start tearing it out now?

**Comment by brigsz** [comment]
well, I think you are probably fine to tear it down, however, I always wonder what I am forgetting about.  Old people! you cannot trust them, they are always shooting themselves in the foot.

**Comment by MichaelAGRC** [comment]
Okay.  I have updated the perms on this item as well so that only sde can see it at the moment.

**Comment by MichaelAGRC** [comment]
I have changed the sharing from Everyone to Owner.  Only UtahAGRC should be able to see it now on AGOL and OpenData.

**Comment by stdavis** [comment]
Should we trash this dataset now? It's been hidden for about a month. @brigsz any issues?

**Comment by brigsz** [comment]
So long, farewell, let it go Scott

**Comment by steveoh** [comment]
@MichaelAGRC or @ZachBeck you'll need to do the datbase/agol deletions. Will you report back when that has been completed?

**Comment by ZachBeck** [comment]
It's gone from SGID, SGID10, and AGOL now.

**Comment by steveoh** [comment]
Does anyone know how to delete https://drive.google.com/drive/folders/0ByStJjVZ7c7mcjFCd0tmcEdHcmM
