### ISSUE TITLE
Deprecate fiberediting.mapserv.utah.gov

### ISSUE THREAD

**Issue by ZachBeck** [agrc/cemetery#19]
Deprecate fiberediting app due to under-utilization. The app has only been used by 1 provider in the past year (on 3/20/2020)

FiberVerification database should remain for the time being.

# Is there a website?

- [x] Archive source code repository (@steveoh)
  - https://github.com/agrc/fiber-verification archived
- [ ] Remove from the web server (initials)
or
- [x] Replace app with a static page with information (@steveoh)
or
- [ ] Redirect somewhere else (intials)

# Is there a map service?

- [ ] Stop (intials)
- [x] Delete (@steveoh)

# Is there a forklift pallet?

- [x] Remove repo (@steveoh)
  - no pallet
- [x] Remove stale data from forklift hashing and receiving (@steveoh)
  - nothing to remove

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh)
  - none
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh)
  - none

**Comment by steveoh** [comment]
A calendar appointment was created to remove the DNS sometime in the future. The permission proxy data was deleted as well. Great job team.

**Comment by nathankota** [comment]
DNS deleted
