### ISSUE TITLE
ECONOMY.TaxAreas2018

### ISSUE THREAD

**Issue by ZachBeck** [agrc/cemetery#26]
# Summary

ECONOMY.TaxAreas2018 has been replaced with ECONOMY.TaxAreas2019 

# Triage

- [x] Data Team Triage (@ZachBeck )
- [x] Dev Team Triage (@steveoh)
- [ ] Cadastre Team Triage

# Remove data from the following areas

~- [ ] ArcGIS Online (@jacobdadams )~
- [x] Internal SGID (@ZachBeck )
~- [ ] SGID10 (assigned to)
- [x] Open SGID (@steveoh )
- [x] Google Drive (@ZachBeck)
- [x] Open data (@jacobdadams )
- [x] Mapserv (@stdavis)

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (@jacobdadams )~
- [x] Move existing AGOL item to AGRC_Shelved AGOL folder (@jacobdadams )
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

- [x] gis.utah.gov data pages (@ZachBeck )
- [x] Stewardship doc and sgid-index (@steveoh )
- [x] `SGID.META.AGOLItems` (@jacobdadams )
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (@jacobdadams )
- [x] `SGID.META.ChangeDetection` (@stdavis )

# Is there a website?

- ~[ ] Archive source code repository (assigned to)~
- ~[ ] Remove from the web server (assigned to)~
or
- ~[ ] Replace app with a static page with information (assigned to)~
or
- ~[ ] Redirect somewhere else (assigned to)~

# Is there a map service?

- ~[ ] Stop (assigned to)~
- ~[ ] Delete (assigned to)~

# Is there a forklift pallet?

- ~[ ] Remove repo (assigned to)~
  `findstr /SIN /d:c:\forklift\warehouse /C:"taxarea" *.py` had no results
- [x] Remove stale data from forklift hashing and receiving (@stdavis)

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh - searched bigquery logs and no queries made)
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh)

# Notification

- [ ] Blog post (assigned to)
- [x] Twitter (@steveoh)
  - [x] Intent
  - [x] Completed

**Comment by steveoh** [comment]
dev triage is in progress. no one is querying this data with the web api since we started logging so it is safe to remove from the sgid10. 

@stdavis this data is in the forklift hash set i believe because of the arcgis online pallet. So I believe after the meta table is updated to the 2019 data we can remove that from hashing and the gis servers.

It appears that the data was updated on the gis data page. I think we should add a related resource section and link to the shelved location for posterity. 

Open sgid data will be removed when the data is removed from internal.

**Comment by jacobdadams** [comment]
Data have been shelved in AGOL. Ready to remove from SDEs.

**Comment by steveoh** [comment]
updated google drive to zach for permission reasons

**Comment by stdavis** [comment]
@jacobdadams This dataset is still in `SGID.META.AGOLItems`. It needs to be removed, no? I just saw your name next to that checked box and wanted to see what's up.

**Comment by jacobdadams** [comment]
Good catch @stdavis! I'm just going to blame it on the VPN ;) They have been properly deleted from `SGID.META.AGOLItems`.

**Comment by stdavis** [comment]
Thanks, @jacobdadams!

I've got the data clean up out of forklift and the change detection table.

**Comment by ZachBeck** [comment]
Deleted from Drive

**Comment by steveoh** [comment]
tweet is out. closing.
