### ISSUE TITLE
ECONOMY.TaxEntities2018

### ISSUE THREAD

**Issue by ZachBeck** [agrc/cemetery#27]
# Summary

ECONOMY.TaxEntities2018 has been replaced with ECONOMY.TaxEntities2019

# Triage

- [x] Data Team Triage (@ZachBeck )
- [x] Dev Team Triage (@stdavis)
- [ ] Cadastre Team Triage
# Remove data from the following areas

~- [ ] ArcGIS Online (@jacobdadams )~
- [x] Internal SGID (@ZachBeck )
~- [ ] SGID10 (assigned to)~
- [x] Open SGID (@steveoh ) - this is automated but we can check it after it is completed.
- [x] Google Drive (@ZachBeck)
- [x] Open data (@jacobdadams )
- [x] Mapserv (@stdavis)

# Copy data to the following areas

~- [ ] Upload to UtahAGRC/AGRC_Shelved folder in AGOL (@jacobdadams )~
- [x] Move existing AGOL item to AGRC_Shelved AGOL folder (@jacobdadams )
~- [ ] Upload to appropriate UtahAGRC/{SGID Category} folder in AGOL (for "static" datasets) (assigned to)~

# Update information in the following areas

- [x] gis.utah.gov data pages (@ZachBeck )
- [x] Stewardship doc and sgid-index (@steveoh )
- [x] `SGID.META.AGOLItems` (@jacobdadams )
- [x] `AGRC_Shelved/AGOLItems_Shelved` (in AGOL) (@jacobdadams )
- [x] `SGID.META.ChangeDetection` (@stdavis)

# Is there a website?

~- [ ] Archive source code repository (assigned to)~
~- [ ] Remove from the web server (assigned to)~
or
~- [ ] Replace app with a static page with information (assigned to)~
or
~- [ ] Redirect somewhere else (assigned to)~
- [x] Update https://github.com/agrc/locate to use the new layer (@stdavis)

# Is there a map service?

~- [ ] Stop (assigned to)~
~- [ ] Delete (assigned to)~

# Is there a forklift pallet?

~- [ ] Remove repo (assigned to)~
~- [ ] update pallet in locate (@stdavis)~
- [x] Remove stale data from forklift hashing and receiving (@stdavis)

# Are there service dependencies?

- [x] Validate that the web api does not query it (@steveoh)
- [x] Validate that AGRC or applications widgets do not reference it (@steveoh)

# Notification

- [ ] Blog post (assigned to)
- [ ] Tweet (@steveoh)
  - [x] Intent Tweet
  - [ ] Completed Tweet

**Comment by steveoh** [comment]
@stdavis do you want to take the rest of this one. I did notice when looking at #26 that locate uses this data so that app will need to be updated.

**Comment by stdavis** [comment]
I've finished the triage. One question: Is this dataset going to be removed entirely from internal and SGID10? I can see a bunch of older version of this dataset in SGID10 but only the 2018 version in internal.

**Comment by jacobdadams** [comment]
I think the intent was that the older versions should not be internal but
should be shelved (hosted in AGOL only).

Jake

**Comment by stdavis** [comment]
What about SGID10?

**Comment by jacobdadams** [comment]
If I'm remembering the discussions correctly, conceptually I think all the
shelved items stay in SGID10 (so we'll always have the old db to fall back
on if we absolutely have to). However, now that I think about that, I
wonder if that breaks/causes headaches with any of the update
scripts/processes.

**Comment by stdavis** [comment]
I think that should be fine with regard to forklift. I just wanted to make sure that we were clear on that. Thx.

**Comment by stdavis** [comment]
I've updated locate.utah.gov to point to the new dataset.

**Comment by jacobdadams** [comment]
Data have been shelved in AGOL. Ready to remove from SDEs.

**Comment by steveoh** [comment]
I see that I am assigned the google drive on here. I do not have access to that so I am going to assign it to zach as I believe he has handled this before.

**Comment by steveoh** [comment]
@ZachBeck i noticed there is no taxareas2019 in the stewardship doc when i added this url to the deprecated field.

**Comment by ZachBeck** [comment]
It's fixed now

**Comment by jacobdadams** [comment]
The consensus is that Shelved data will remain in SGID10, allowing that database to contain all the datasets it had before we started the transition to the new SGID.

**Comment by ZachBeck** [comment]
Deleted from Google Drive

**Comment by steveoh** [comment]
i think that is everything then. Please reopen if I am wrong.
