### ISSUE TITLE
yes or no checkboxes

### ISSUE THREAD

**Issue by steveoh** [agrc/cemetery#3]
### Describe the problem you are having

I cannot tell from the checkboxes if the answer is yes or no or if it's been taken care of. Do we need to make that more clear?

for instance, when a deprecation doesn't have a github, website etc, do one of us check them off anyway since we looked?

are we conveying that we identified the places that need work or that the work has been done.

**Comment by ZachBeck** [comment]
Some of that stuff will be unknown to the person filling it out. I'm not sure what feature classes are part of a pallet or if there are service dependencies etc. Maybe yes, no, unknown (y, n, u).

**Comment by steveoh** [comment]
I think it is ok if you intentionally skip items because they are not your responsibility. I think the question is more of when you do check the box, are you identifying that work needs to be done or that you completed the work.

**Comment by stdavis** [comment]
I had the same concern. Maybe the verbiage needs to make it sound more like an action item that has been completed and we just remove everything that's not relevant? If you're not sure if it's relevant or not, leave it and someone else can remove it.
